set.seed(20230201)
mydata <- arima.sim(n=1000,list(ar=c(0.439,0.206,-0.156)))
library(weakARMA)
fit <- estimation(p=3,q=0,y=mydata,meanparam = TRUE)
model_test = portmanteauTest(ar = fit$ar, y = mydata, m = 20)
fit2 <- estimation(p=1,q=0,y=mydata,meanparam = TRUE)
model_test2 = portmanteauTest(ar = fit2$ar, y = mydata, m = 20)
plot(model_test$PvalLB.Imhof,ylim = c(0,1),xlab = "Lag",ylab = "p value",main = "p values for modified Ljung-Box test")
abline(h = 0.05, col = "blue",lty=2)
plot(model_test2$PvalLB.Imhof,ylim = c(0,1),xlab = "Lag",ylab = "p value",main = "p values for modified Ljung-Box test")
abline(h = 0.05, col = "blue",lty=2)